[package]
name = "chess_trainer"
version = "0.1.0"
authors = ["Rettdog <30802926+Rettdog@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "0.15.6"
rand = "0.8.3" 